INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `fecha_egreso`, `Turno`) VALUES ('Lou', 'Hedon', '2022-12-15', '2023-01-17', 'Mañana');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `fecha_egreso`, `Turno`) VALUES ('Magda', 'Titterington', '2022-12-17', '2023-02-02', 'Tarde');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `Turno`) VALUES ('Kym', 'Churchill', '2022-12-18', 'Tarde');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `Turno`) VALUES ('Helsa', 'Gerretsen', '2023-01-20', 'Mañana');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `fecha_egreso`, `Turno`) VALUES ('Rakel', 'Dady', '2022-12-11', '2023-04-18', 'Mañana');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `fecha_egreso`, `Turno`) VALUES ('Geralda', 'Nosworthy', '2023-04-03', '2023-04-30', 'Mañana');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `fecha_egreso`, `Turno`) VALUES ('Dunn', 'Gillibrand', '2023-01-16', '2023-04-04', 'Tarde');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `Turno`) VALUES ('Sarge', 'Palley', '2023-01-14', 'Tarde');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `fecha_egreso`, `Turno`) VALUES ('Carlo', 'Thebe', '2023-01-26', '2023-04-16', 'Tarde');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `fecha_egreso`, `Turno`) VALUES ('Dorita', 'Wooder', '2022-12-02', '2023-03-19', 'Mañana');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `Turno`) VALUES ('Ryon', 'Stobie', '2023-01-27', 'Tarde');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `Turno`) VALUES ('Marcelo', 'Dongall', '2023-02-08', 'Mañana');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `fecha_egreso`, `Turno`) VALUES ('Trenton', 'Bullick', '2023-04-12', NULL, 'Mañana');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `Turno`) VALUES ('Michaela', 'Matura', '2022-12-28', 'Tarde');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `fecha_egreso`, `Turno`) VALUES ('Francisco', 'Sparshutt', '2022-12-12', '2023-03-12', 'Tarde');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `Turno`) VALUES ('Sharyl', 'Georgeot', '2023-02-23', 'Mañana');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `Turno`) VALUES ('Manny', 'Tolley', '2023-03-16', 'Tarde');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `Turno`) VALUES ('Heida', 'Newvill', '2023-02-21', 'Mañana');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `Turno`) VALUES ('Sammy', 'Badam', '2023-02-06', 'Mañana');
INSERT INTO `emprendimiento_ropa`.`empleado` (`Nombre`, `Apellido`, `fecha_ingreso`, `fecha_egreso`, `Turno`) VALUES ('Georgie', 'Thomsen', '2022-12-17', '2023-04-20', 'Tarde');
